### PR TITLE
Upgrade whoops exception handler

### PR DESCRIPTION
**Pull request by shadowhand**
Version 2.x looks nicer and has better config options.

### CODE REVIEW

**Comment by shadowhand** [comment]
This is not backwards compatible and will need to go into 2.x.

**Comment by elazar** [comment]
@shadowhand It's breaks BC in a way that affects our code in Equip? Seems surprising considering how few changes this PR makes.

**Comment by shadowhand** [comment]
@elazar well... our own code is BC, but the changes in Whoops are breaking. Not sure how specific we want to be about that.

**Comment by shadowhand** [comment]
I guess [semver item 7](http://semver.org/#spec-item-7) would allow it, since the public API does not change.

**Comment by elazar** [comment]
:+1:

**Pull request merged**
