### PR TITLE
Use the trait for Resolver in ActionHandler

### PR DESCRIPTION
**Pull request by AlexMasterov**

### CODE REVIEW

**Comment by shadowhand** [comment]
Why would this be necessary?

**Comment by AlexMasterov** [comment]
@shadowhand It's just respect the DRY principle (aka "Don't Repeat Yourself").

Some Responders have the same case, and there it was useful. Where else to use this trait as not here?

**Comment by shadowhand** [comment]
Ah my mistake, I was going through PRs too fast. This looks reasonable.

**Comment by shadowhand** [comment]
👍

**Pull request merged**
