### PR TITLE
Relocate configuration code to equip/config

### LINKED ISSUE #68: Move core configuration code to separate library?
I'd like to be able to use the core configuration code (i.e. `ConfigurationInterface` and `ConfigurationSet`) apart from the rest of the framework. I think there may be sufficient value in this notion to warrant moving it to its own repository.

It's under its own sub-namespace, so no namespace changes would be needed. The only potential difficulty I can see that it introducing is that any major version upgrades to `equip/structure` dependency would have to be done on both repositories simultaneously to avoid version conflicts.

### PR DESCRIPTION
**Pull request by elazar**
Fixes #68

### CODE REVIEW

**Comment by sctape** [comment]
👍

**Comment by ameech** [comment]
👍

**Comment by shadowhand** [comment]
Whoa whoa whoa! This is exactly what I said __could not be done__ to the 2.x branch. These changes can only be applied to `dev` branch otherwise we are removing functionality in a minor release.

Please revert and apply to the correct branch!

**Comment by elazar** [comment]
@shadowhand I don't follow. What functionality is being removed? The code is simply being relocated. None of the namespaces have changed. All previous tagged versions still have the code, any subsequent versions should pull identical code from equip/config. The only change is where it's located in the vendor directory, which shouldn't matter because the autoloader will still be able to load it.

**Comment by shadowhand** [comment]
@elazar my bad, I thought this was https://github.com/elazar/auryn-configuration/

**Pull request merged**
