### PR TITLE
Small refactoring

### PR DESCRIPTION
**Pull request by AlexMasterov**

### CODE REVIEW

**Comment by shadowhand** [comment]
I'm undecided on this one... it does make things more consistent, but I'm not entirely sure that it is more consistent in the right way. I need to think about it more.

**Comment by AlexMasterov** [comment]
@shadowhand: meditate on this: [`ActionHandler`](https://github.com/equip/framework/blob/d8112d22fd200c54150209f6f98a494f04a155e4/src/Handler/ActionHandler.php#L98) and [`ExceptionHandler`](https://github.com/AlexMasterov/framework/blob/5be6b87cd3ab85eb78a08e40b523cf82e5c58112/src/Handler/ExceptionHandler.php#L131).

This looks like a good practice, the same sort: `(request, response, payload/exception)`

**Comment by AlexMasterov** [comment]
I'm still hoping for a merge.
Need to make methods as private and declare the class as final. Then there will be no doubt. :smile:

**Comment by shadowhand** [comment]
👍

**Pull request merged**
