### PR TITLE
Delete all responders and related configuration

### PR DESCRIPTION
**Pull request by shadowhand**
The ADR triad is not meant to be implemented in an agnostic way, but
rather implemented exactly as necessary for each use case. This makes
general purpose responders pointless, since the responder attached to
each action (or possibly groups of actions) will generate an exact
response based on the requirements of the use case.

Refs #75

### CODE REVIEW

**Comment by shadowhand** [comment]
I'm not certain this should be immediately merged down to the simplified branch. In particular, I would like to find a reasonable way to preserve the content negotiation that is available in [`FormattedResponder`](https://github.com/equip/framework/blob/2b03d8ac28708955cf2e0da6b8e33168183072ce/src/Responder/FormattedResponder.php#L100-L113).

Anyone have suggestions on how we can create content negotiation within the context of formatters instead of responders?

**Comment by elazar** [comment]
@shadowhand Maybe shift them to middlewares placed into the pipeline after `ActionHandler` ?

**Comment by shadowhand** [comment]
@elazar no, the responder attached to the action should do the formatting. ActionHandler should always produce a full populated response.

**Comment by elazar** [comment]
@shadowhand Fair enough. In that case, I guess we can look at either composing supporting classes or using traits in responder classes.

**Comment by bvisness** [comment]
@shadowhand It seems to me that content negotiation belongs in the responders because it's effectively choosing what format to use, which implies things like `Content-Type` headers, etc. in the response.

**Comment by bvisness** [comment]
@shadowhand And besides, `format($content)` just returns a string, and the `type()` method doesn't take any arguments, so without some major changed to `FormatterInterface`, I don't see how you could implement content negotiation there at all.

**Comment by shadowhand** [comment]
@elazar will do responder doc updates here before merging.

**Comment by shadowhand** [comment]
@bvisness I believe your concerns were addressed in #78

**Comment by shadowhand** [comment]
@elazar docs have been updated in #79

**Comment by elazar** [comment]
👍

**Pull request merged**
